### Log ind med en bruger
POST http://localhost:7000/api/auth/login
Content-Type: application/json

{
  "email": "admin",
  "password": "1234"
}

### Registrering af en bruger
POST http://localhost:7000/api/auth/register
Content-Type: application/json

{
  "email": "admin",
  "password": "1234"
}

### Get all recipe
GET http://localhost:7000/api/recipe

### Get recipe by id
GET http://localhost:7000/api/recipe/1

### Get recipe by email/username
GET http://localhost:7000/api/recipe/personal/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NTgyOTYsImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJhZG1pbiJdfQ.3R9TkwDwFq10-LBgbS4EY4GYWBuD2jznlufhP2xBl9k

### Upload recipe
POST http://localhost:7000/api/recipe/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NTkyNTQsImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJ1c2VyIl19.5rQwHABO5pcoPgJCo3kiyN0WhG4yf5mm8SzzN2V7KUU

{
  "name": "kagasde",
  "ingredients": "5 æg og 1asdasd kg mel",
  "instructions": "Bland æg og masdasdel sammen",
  "user": {
     "email": "admin"
  }
}

### Update recipe
PUT http://localhost:7000/api/recipe/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NDU4MjksImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJ1c2VyIl19.a_fYu2ysQ3schjpDjBkAn-q8YbnfGrD71W6op2aX9Qs

{
  "id": 1,
  "name": "kage",
  "ingredients": "5 æg og 1 kg mel",
  "instructions": "Bland æg og mel sammen og bag i ovnen"
}

### Delete recipe
DELETE http://localhost:7000/api/recipe/admin
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NDU4MjksImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJ1c2VyIl19.a_fYu2ysQ3schjpDjBkAn-q8YbnfGrD71W6op2aX9Qs

2

### Add role to user
POST http://localhost:7000/api/auth/addroletouser
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NDYxMzEsImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJhZG1pbiJdfQ.1P8vhOjF1BQG-XfpcELzTJyE8LSJLJodTg7WpbufGFM

{
"email": "admin",
"role": "admin"
}

### Get all roles
GET http://localhost:7000/api/auth/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NDYxMzEsImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJhZG1pbiJdfQ.1P8vhOjF1BQG-XfpcELzTJyE8LSJLJodTg7WpbufGFM

### Get all users
GET http://localhost:7000/api/auth/users
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NDU4MjksImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJ1c2VyIl19.a_fYu2ysQ3schjpDjBkAn-q8YbnfGrD71W6op2aX9Qs

### Slet en bruger
DELETE http://localhost:7000/api/auth/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NDU4MjksImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJ1c2VyIl19.a_fYu2ysQ3schjpDjBkAn-q8YbnfGrD71W6op2aX9Qs

"sd"

### post comment for recipe id1

POST http://localhost:7000/api/comment/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NTkyNTQsImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJ1c2VyIl19.5rQwHABO5pcoPgJCo3kiyN0WhG4yf5mm8SzzN2V7KUU
email: admin

{
  "text": "This is a commen21."
}

### Get comment by recipe id1
GET http://localhost:7000/api/comment/1

### make foverrit by /favorite/{user_email}/{recipe_id}
POST http://localhost:7000/api/recipe/favorite/admin/4/
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJHcnVwcGU0Iiwic3ViIjoiYWRtaW4iLCJleHAiOjE3MTY4NTkyNTQsImVtYWlsIjoiYWRtaW4iLCJyb2xlcyI6WyJ1c2VyIl19.5rQwHABO5pcoPgJCo3kiyN0WhG4yf5mm8SzzN2V7KUU

